#!/bin/sh

start() {
	if test -z "$1"
	then
		usage
	fi
}

_stop() {
	echo 0
}

usage() {
	echo 'usage: evertime <command> [<arg>]'
	exit 1
}

main() {
	mkdir -p 'db/'
	case $1 in
		start)  start "$2";;
		stop)   _stop;;
		*)      usage;;
	esac
}

main "$@"
