#!/bin/sh

tmp_path='/tmp/evertime'

start() {
	if test -z "$1"
	then
		usage
	fi
	( ./evertime '__sh' "$1" & )
}

_stop() {
	if test -f $tmp_path
	then
		kill "$(head -1 $tmp_path)"
		rm -f $tmp_path
	fi
}

usage() {
	echo 'usage: evertime <command> [<arg>]'
	exit 1
}

__sh() {
	echo $$ > $tmp_path
	while true
	do
		sleep 10
	done
}

main() {
	mkdir -p 'db/'
	case $1 in
		start)  start "$2";;
		stop)   _stop;;
		*)      usage;;
	esac
}

if test '__sh' = "$1"
then
	__sh "$2"
else
	main "$@"
fi
