#!/bin/sh

sem=0
tmp='/tmp/evertime'
dbp=$HOME'/.evertime'

start() {
	test -n "$1" || usage
	( ./evertime '__sh' "$1" & )
}

stats() {
	test -n "$1" || usage

	while read -r _in out _
	do
		acc=$((acc + out - _in))
		echo "$(date -d @$((out - _in)) -u '+%H-%M')  $(date -d "@$_in" '+%Y-%m-%d %H:%M')"
	done < "$dbp/$1"

	date -d "@$acc" -u '+%H:%M'
}

_stop() {
	if test -f $tmp
	then
		kill "$(cat $tmp)"
		rm $tmp
	fi
}

usage() {
	echo 'Usage: evertime <command> [<arg>]' 1>&2
	exit 1
}

proc() {
	fn=$dbp/$1
	rp='([0-9]*) ([0-9]*) <'

	echo $$ > $tmp
	echo "$(date +%s) $(date +%s) <" >> "$fn"

	while [ $sem = 0 ]
	do
		sleep 1m
		sed -i -E "s/$rp/\1 $(date +%s) </g" "$fn"
	done

	sed -i -E "s/$rp/\1 \2/g" "$fn"
}

main() {
	mkdir -p "$dbp"
	case $1 in
		start)  start "$2";;
		stats)  stats "$2";;
		stop)   _stop;;
		*)      usage;;
	esac
}

if test '__sh' = "$1"
then
	trap 'sem=1' TERM
	proc "$2"
else
	main "$@"
fi
